name: Create GitHub release

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  create-release:
    # This workflow is only of value to PyBaMM and would always be skipped in forks
    if: github.repository_owner == 'pybamm-team'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3

    - name: Get current date
      run: |
        echo "VERSION=$(date +'v%y.%-m')" >> $GITHUB_ENV
        echo "TODAY=$(date +'%d')" >> $GITHUB_ENV

    - name: Fail the job if date < 20
      if: env.TODAY < 20
      uses: actions/github-script@v5
      with:
        script: core.setFailed('This workflow should be triggered only at the end of the month, or else it will create a release for the wrong month.')

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install wheel
        pip install --editable .

    - name: Get Changelog
      run: python -c "from scripts.update_version import get_changelog; get_changelog()"

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        body_path: CHANGELOG.md
